[package]
name = "audio_server"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"
description = "Sound Garden Audio Synth Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "audio_server"
path = "./src/lib.rs"

[dependencies]
alloc_counter = "0.0.4"
anyhow = "1.0.28"
chrono = "0.4.11"
cpal = "0.11.0"
clap = "2.33.0"
crossbeam-channel = "0.4.2"
hound = "3.4.0"
ringbuf = "0.2.1"
serde_json = "1.0.51"

[dependencies.serde]
version = "1.0.106"
features = ["derive"]

[dependencies.audio_ops]
path = "../audio_ops"

[dependencies.audio_program]
path = "../audio_program"

[dependencies.audio_vm]
path = "../audio_vm"

[dependencies.thread_worker]
path = "../thread_worker"
