[package]
name = "sound-garden-0x2"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"

[workspace]

members = [
    "audio_ops",
    "audio_program",
    "audio_server",
    "audio_vm",
    "play_program",
    "render_program",
    "sound_garden_terminal",
    "sound_garden_vst",
    "thread_worker"
]

[profile.release]
lto = true
panic = "abort"
