[package]
name = "sound_garden_druid"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.10.0"
anyhow = "1.0.19"
thiserror = "1.0.5"
crossbeam-channel = "0.4.0"
rand = "0.7.2"
serde_cbor = "0.10.2"
base64 = "0.11.0"
clipboard = "0.5.0"
brotli = "3.3.0"
druid = "0.3.2"
piet-cairo = "0.0.7"
toml = "0.5.5"
log = "0.4.8"
serde_json = "1.0.41"
fake = "2.2.0"

[dependencies.serde]
version = "1.0.102"
features = ["derive"]

[dependencies.simple_logger]
version = "1.3.0"
default-features = false

[dependencies.audio_ops]
path = "../audio_ops"

[dependencies.audio_program]
path = "../audio_program"

[dependencies.audio_vm]
path = "../audio_vm"
